---

apiVersion: v1
kind: Secret
metadata:
  name: {{.Values.serviceName}}-secret
  namespace: {{.Values.serviceName}}
type: Opaque
data:
  host: {{ default "" .Values.mysql.host | b64enc | quote }}
  user: {{ default "" .Values.mysql.user | b64enc | quote }}
  pass: {{ default "" .Values.mysql.pass | b64enc | quote }}
  db: {{ default "" .Values.mysql.db | b64enc | quote }}
