kind: Service
apiVersion: v1
metadata:
  name: {{.Values.serviceName}}
spec:
  selector:
    app: {{.Values.serviceName}}
    type: backend
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
