FROM php:8.0.5-fpm-buster
MAINTAINER beliys "https://github.com/beliys/Anemometer"

ARG PREPARE_TESTS=false
ARG PHP_EXTENSIONS="mysqli bcmath opcache"

# Install dependencies
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    bash && \
    docker-php-ext-install $PHP_EXTENSIONS && \
    docker-php-source delete && \
    apt-get clean autoclean && \
    apt-get autoremove --yes && \
    rm -rf /var/lib/{apt,dpkg,cache,log}/

# Use the production configuration
RUN mv "$PHP_INI_DIR/php.ini-production" "$PHP_INI_DIR/php.ini"

# copy php configs
COPY ./docker/fpm/modules /usr/local/etc/php/conf.d
COPY ./docker/fpm/php-fpm.d /usr/local/etc/php-fpm.d

# Copy web-app files
COPY ./src /var/www/html
COPY ./docker/fpm/conf /var/www/html/conf

# Copy tests folder
COPY ./tests /tests

RUN if [ "${PREPARE_TESTS}" = "true" ]; then \
      cp -rf /tests/* /var/www/html && \
			cd /var/www/html && \
			curl -sS https://getcomposer.org/composer.phar -o /usr/local/bin/composer && \
			chmod +x /usr/local/bin/composer && \
			/usr/local/bin/composer install; \
	  else \
		  rm -rf /tests; \
		fi

WORKDIR /var/www/html

# Rewrite signal. Kubernetes always sends SIGTERM signal, fpm use SIGQUIT for graceful shutdown.
STOPSIGNAL SIGQUIT

CMD ["php-fpm"]
